version: "3.8"

services:
  app:
    tty: true
    stdin_open: true
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - 8080:3000 
    volumes:
      - '.:/app'
      - '/app/node_modules'